# Flutter/Dart analysis options for AquaTrack

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Prefer const constructors
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    
    # Avoid print statements in production
    avoid_print: true
    
    # Prefer single quotes
    prefer_single_quotes: true
    
    # Always use required named parameters
    always_require_non_null_named_parameters: true
    
    # Sort child properties last
    sort_child_properties_last: true

analyzer:
  errors:
    # Treat missing returns as errors
    missing_return: error
    
    # Treat unused imports as warnings
    unused_import: warning
    
    # Treat unused local variables as warnings
    unused_local_variable: warning
  
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
